# Generated by Django 2.0.7 on 2018-08-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('photologue', '0011_auto_20180826_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('photologue.gallery',),
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('photologue.photo',),
        ),
    ]
