# Generated by Django 2.0.7 on 2018-08-13 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('Bachelor Party', 'Bachelor Party'), ('Bachelorette Party', 'Bachelorette Party'), ('Bridal Shower', 'Bridal Shower'), ('Church Service', 'Church Service'), ('Reception', 'Reception')], max_length=20)),
                ('guest', models.CharField(choices=[('00', '00'), ('01', '01'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05')], max_length=2)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Rsvp',
                'verbose_name_plural': 'Events Rsvp',
            },
        ),
    ]
