# Generated by Django 2.0.7 on 2018-08-13 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_auto_20180813_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventrsvp',
            name='event',
            field=models.CharField(choices=[('Church Service', 'Church Service'), ('Bachelor Party', 'Bachelor Party'), ('Bachelorette Party', 'Bachelorette Party'), ('Bridal Shower', 'Bridal Shower'), ('Reception', 'Reception')], default='Church Service', max_length=20),
        ),
    ]
