# Generated by Django 2.0.7 on 2018-08-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmed_date',
            field=models.DateTimeField(),
        ),
    ]
