# Generated by Django 2.0.7 on 2018-08-04 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180804_0508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmed_date',
        ),
    ]
